sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - yarn
notifications:
  email: true
node_js:
  - stable
before_script:
  - npm prune
after_success:
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

