blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://github.com/jmuelbert/generator-swift/wiki/FAQ
    about: You may find your question and the answer to it here.
  - name: Documentation
    url: http://jmuelbert.github.io/generator-swift/
    about: The documentation tells you how to use generator-swift.
