name: "CI: Build Test"

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Test
      shell: pwsh
      run: npm run coveralls
