name: "CI: Build Test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run test
        env:
          CI: true      
      - run: npm run lint
      - name: coverage
        run: |
          npm run coverage
          npm run report-coverage
      - uses: codecov/codecov-action@v2.0.1
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
