---
# SPDX-FileCopyrightText: (c) Wagner Santos
#
# SPDX-License-Identifier: MIT
#
name: Lint Commit Messages
on: [pull_request] # yamllint disable-line rule:truthy

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Checkout"
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: "Check the commits"
        uses: wagoid/commitlint-github-action@7f0a61df502599e1f1f50880aaa7ec1e2c0592f2 # v6.0.1
