---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT

name: "Misspell fixer"

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release, improve_workflows]

  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          # Full git history is needed to get a proper list of changed
          # files within `super-linter`
          fetch-depth: 0

      - name: Run Misspell Fixer
        uses: sobolevn/misspell-fixer-action@26173e641ba08255d0c9826b8a873f8b96f76932 # master

      - name: Check for changes
        run: git diff --exit-code ${{ github.sha }}

      - name: Create Pull Request for typos
        if: failure()
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          commit-message: "Fix typos by misspell-fixer"
          title: "Fix typos by misspell-fixer for ${{ github.ref }}"
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: "auto-pr/misspell-fixer/${{ github.ref }}"
