name: pre-commit

on:
  push:
    branches: [main, develop, release, improve_build-workflow]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: "🐍 Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x

      - name: "Perform Pre-Commit"
        uses: pre-commit/action@v3.0.1
