name: pre-commit

on:
  push:
    branches: [main, develop, release, improve_build-workflow]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: "🐍 Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x

      - name: "Perform Pre-Commit"
        uses: pre-commit/action@v3.0.1
