---
# SPDX-FileCopyrightText: Jürgen Mülbert <juergen.muelbert@web.de>
#
# SPDX-License-Identifier: EUPL-1.2

name: REUSE Compliance Check

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release, improve_build-workflow]

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can
    # default to all as well
    types: [opened, reopened, synchronize]
    # pull_request_target event is required for autolabeler to
    # support PRs from forks
    # pull_request_target:

permissions:
  contents: read

jobs:
  ReuseCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@a46482ca367aef4454a87620aa37c2be4b2f8106 # v3.0.0
